### ISSUE TITLE
Increase file upload size?

### ISSUE THREAD

**Issue by hassankhan** [dbpolito/firestead#1]
I know Homestead sets it to 8M, but that's not realistic for most of us, and Laravel throws a `TokenMismatchException` which doesn't help figuring out what the issue is.

**Comment by dbpolito** [comment]
@hassankhan Thanks for reporting this, i opened i PR https://github.com/laravel/settler/pull/41 which fix this issue to everyone, not only firestead users...

Lets see if taylor merges it, if not, i will make this change here.

**Comment by dbpolito** [comment]
Woohooo, merged! You'll see this fixed when taylor tags a new version at https://atlas.hashicorp.com/laravel/boxes/homestead
